/**
 * RED Metrics from OpenTelemetry Spans
 *
 * Derives RED metrics (Rate, Errors, Duration) from Tempo span metrics generator.
 * These metrics are automatically generated by Tempo from incoming spans and
 * exported to Prometheus for querying and alerting.
 *
 * RED Metrics:
 * - Rate: Requests per second (throughput)
 * - Errors: Error rate percentage
 * - Duration: Latency percentiles (P50, P95, P99)
 *
 * Architecture:
 * OpenTelemetry Spans -> Tempo -> Metrics Generator -> Prometheus -> Grafana
 *
 * @module span-metrics
 */

/**
 * Configuration for RED metrics queries
 */
export interface RedMetricsConfig {
	/** Service name to filter metrics */
	serviceName: string;
	/** Time range for rate calculations (e.g., '5m', '1h') */
	interval?: string;
	/** HTTP method filter (optional) */
	httpMethod?: string;
	/** HTTP route filter (optional) */
	httpRoute?: string;
	/** Deployment environment (development, staging, production) */
	environment?: string;
}

/**
 * SLO thresholds for service health
 */
export interface SloThresholds {
	/** Availability target (e.g., 0.999 for 99.9%) */
	availability: number;
	/** P95 latency target in milliseconds */
	p95LatencyMs: number;
	/** P99 latency target in milliseconds */
	p99LatencyMs: number;
	/** Error rate threshold (e.g., 0.001 for 0.1%) */
	maxErrorRate: number;
}

/**
 * Default SLO thresholds
 */
export const DEFAULT_SLO: SloThresholds = {
	availability: 0.999,
	p95LatencyMs: 500,
	p99LatencyMs: 1000,
	maxErrorRate: 0.001
};

/**
 * Build PromQL query for request rate (requests per second)
 */
export function buildRateQuery(config: RedMetricsConfig): string {
	const { serviceName, interval = '5m', httpMethod, httpRoute, environment } = config;

	const labels: string[] = [`service_name="${serviceName}"`];
	if (httpMethod) labels.push(`http_method="${httpMethod}"`);
	if (httpRoute) labels.push(`http_route="${httpRoute}"`);
	if (environment) labels.push(`deployment_environment="${environment}"`);

	return `rate(tempo_spanmetrics_calls_total{${labels.join(',')}}[${interval}])`;
}

/**
 * Build PromQL query for error rate (percentage of failed requests)
 */
export function buildErrorRateQuery(config: RedMetricsConfig): string {
	const { serviceName, interval = '5m', httpMethod, httpRoute, environment } = config;

	const labels: string[] = [`service_name="${serviceName}"`];
	if (httpMethod) labels.push(`http_method="${httpMethod}"`);
	if (httpRoute) labels.push(`http_route="${httpRoute}"`);
	if (environment) labels.push(`deployment_environment="${environment}"`);

	const baseLabels = labels.join(',');
	const errorLabels = [...labels, 'span_status_code="ERROR"'].join(',');

	return `(
		rate(tempo_spanmetrics_calls_total{${errorLabels}}[${interval}])
		/
		rate(tempo_spanmetrics_calls_total{${baseLabels}}[${interval}])
	)`;
}

/**
 * Build PromQL query for latency percentile
 */
export function buildLatencyQuery(config: RedMetricsConfig, percentile: number): string {
	const { serviceName, interval = '5m', httpMethod, httpRoute, environment } = config;

	const labels: string[] = [`service_name="${serviceName}"`];
	if (httpMethod) labels.push(`http_method="${httpMethod}"`);
	if (httpRoute) labels.push(`http_route="${httpRoute}"`);
	if (environment) labels.push(`deployment_environment="${environment}"`);

	const baseLabels = labels.join(',');

	return `histogram_quantile(
		${percentile},
		rate(tempo_spanmetrics_duration_milliseconds_bucket{${baseLabels}}[${interval}])
	)`;
}

/**
 * Build PromQL query for average latency
 */
export function buildAvgLatencyQuery(config: RedMetricsConfig): string {
	const { serviceName, interval = '5m', httpMethod, httpRoute, environment } = config;

	const labels: string[] = [`service_name="${serviceName}"`];
	if (httpMethod) labels.push(`http_method="${httpMethod}"`);
	if (httpRoute) labels.push(`http_route="${httpRoute}"`);
	if (environment) labels.push(`deployment_environment="${environment}"`);

	const baseLabels = labels.join(',');

	return `(
		rate(tempo_spanmetrics_duration_milliseconds_sum{${baseLabels}}[${interval}])
		/
		rate(tempo_spanmetrics_duration_milliseconds_count{${baseLabels}}[${interval}])
	)`;
}

/**
 * Build PromQL query for availability
 */
export function buildAvailabilityQuery(config: RedMetricsConfig): string {
	const errorRateQuery = buildErrorRateQuery(config);
	return `1 - (${errorRateQuery})`;
}

/**
 * Build PromQL query for error budget consumption
 */
export function buildErrorBudgetQuery(config: RedMetricsConfig, slo: SloThresholds): string {
	const errorRateQuery = buildErrorRateQuery(config);
	const errorBudget = 1 - slo.availability;
	return `(${errorRateQuery}) / ${errorBudget}`;
}

/**
 * Build PromQL alert rule for error rate threshold
 */
export function buildErrorRateAlert(
	config: RedMetricsConfig,
	threshold: number,
	_duration: string = '5m'
): string {
	const errorRateQuery = buildErrorRateQuery(config);
	return `(${errorRateQuery}) > ${threshold}`;
}

/**
 * Build PromQL alert rule for latency threshold
 */
export function buildLatencyAlert(
	config: RedMetricsConfig,
	percentile: number,
	thresholdMs: number,
	_duration: string = '5m'
): string {
	const latencyQuery = buildLatencyQuery(config, percentile);
	return `(${latencyQuery}) > ${thresholdMs}`;
}

/**
 * Build complete RED metrics queries for a service
 */
export function buildRedMetricsQueries(config: RedMetricsConfig) {
	return {
		rate: buildRateQuery(config),
		rateByMethod: buildRateQuery({ ...config, httpMethod: undefined }) + ' by (http_method)',
		rateByRoute: buildRateQuery({ ...config, httpRoute: undefined }) + ' by (http_route)',
		errorRate: buildErrorRateQuery(config),
		errorRateByMethod:
			buildErrorRateQuery({ ...config, httpMethod: undefined }) + ' by (http_method)',
		errorRateByRoute:
			buildErrorRateQuery({ ...config, httpRoute: undefined }) + ' by (http_route)',
		errorCount: `rate(tempo_spanmetrics_calls_total{service_name="${config.serviceName}",span_status_code="ERROR"}[${config.interval || '5m'}])`,
		avgLatency: buildAvgLatencyQuery(config),
		p50: buildLatencyQuery(config, 0.5),
		p95: buildLatencyQuery(config, 0.95),
		p99: buildLatencyQuery(config, 0.99),
		p999: buildLatencyQuery(config, 0.999),
		availability: buildAvailabilityQuery(config),
		uptime: `avg_over_time((${buildAvailabilityQuery(config)})[24h])`
	};
}

/**
 * Build SLO alert rules for a service
 */
export function buildSloAlerts(config: RedMetricsConfig, slo: SloThresholds = DEFAULT_SLO) {
	return {
		errorRateHigh: buildErrorRateAlert(config, slo.maxErrorRate, '5m'),
		errorRateCritical: buildErrorRateAlert(config, slo.maxErrorRate * 2, '1m'),
		p95LatencyHigh: buildLatencyAlert(config, 0.95, slo.p95LatencyMs, '5m'),
		p99LatencyHigh: buildLatencyAlert(config, 0.99, slo.p99LatencyMs, '5m'),
		p99LatencyCritical: buildLatencyAlert(config, 0.99, slo.p99LatencyMs * 2, '1m'),
		availabilityLow: `(${buildAvailabilityQuery(config)}) < ${slo.availability}`,
		errorBudgetConsuming: `(${buildErrorBudgetQuery(config, slo)}) > 0.5`,
		errorBudgetExhausted: `(${buildErrorBudgetQuery(config, slo)}) > 1.0`
	};
}

/**
 * Helper to format percentile value for display
 */
export function formatPercentile(percentile: number): string {
	if (percentile === 0.5) return 'P50';
	if (percentile === 0.95) return 'P95';
	if (percentile === 0.99) return 'P99';
	if (percentile === 0.999) return 'P999';
	return `P${(percentile * 100).toFixed(1)}`;
}

/**
 * Helper to format error rate as percentage
 */
export function formatErrorRate(errorRate: number): string {
	return `${(errorRate * 100).toFixed(2)}%`;
}

/**
 * Helper to format latency in milliseconds
 */
export function formatLatency(latencyMs: number): string {
	if (latencyMs < 1) {
		return `${(latencyMs * 1000).toFixed(2)}us`;
	}
	if (latencyMs < 1000) {
		return `${latencyMs.toFixed(2)}ms`;
	}
	return `${(latencyMs / 1000).toFixed(2)}s`;
}

/**
 * Helper to check if metric violates SLO
 */
export function violatesSlo(
	metricType: 'errorRate' | 'p95' | 'p99' | 'availability',
	value: number,
	slo: SloThresholds = DEFAULT_SLO
): boolean {
	switch (metricType) {
		case 'errorRate':
			return value > slo.maxErrorRate;
		case 'p95':
			return value > slo.p95LatencyMs;
		case 'p99':
			return value > slo.p99LatencyMs;
		case 'availability':
			return value < slo.availability;
		default:
			return false;
	}
}
